name: Ansible pipeline

# manually trigger the docker build and publish pipeline
on: workflow_dispatch

jobs:
  playground:
    name: playground
    runs-on: ubuntu-20.04
    steps:
    - name: Ansible version
      run: ansible --version
