name: Build & Publish Docker Image

# manually trigger the docker build and publish pipeline
on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'The tag for the image'
        required: true
        default: 'latest' 
        type: string

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: biswajee/heroku-opa-server

jobs:
  build-and-push-image:
    name: Build & Push
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout biswajee/heroku-opa-server
      uses: actions/checkout@v2
      with:
        repository: biswajee/heroku-opa-server
        ref: refs/heads/master
        path: opa-server

    - name: Log in to the container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata labels for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    - name: Build and push docker image with tag '${{ steps.meta.outputs.tags }}'
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      if: github.ref == 'refs/heads/master'
      with:
        context: opa-server
        push: true
        tags: ${{ github.event.inputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
